name: Versioning Action
description: Sets up contents of sources in versioned format for pushing to wordlake
inputs:
  prebuild:
    description: 'The name of the wordlake (wordlake, wordlake-staging, wordlake-dev)'
    required: true
  site-repo:
    description: 'The name of the site repo'
    required: true
  content-repo:
    description: 'The name of the content repo'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
