name: Configure Versioned Prebuild Repo
description: Setup Node, checkout, and install dependencies before configuring the repo
inputs:
  prebuild:
    description: Prebuild configuration
    required: true
  site-repo:
    description: Site repository name
    required: true
  content-repo:
    description: Content repository name
    required: true
  base-ref:
    description: Base reference for checkout
    required: true
  workspace:
    description: Path to current workspace
    required: true
runs:
  using: composite
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install versioning action dependencies
      run: npm install
      shell: bash
      working-directory: workflows/.github/actions/version-content

    - name: Execute versioning action
      run: node ./index.js
      shell: bash
      working-directory: workflows/.github/actions/version-content
      env:
        PREBUILD: ${{ inputs.prebuild }}
        SITE_REPO: ${{ inputs.site-repo }}
        CONTENT_REPO: ${{ inputs.content-repo }}
        BASE_REF: ${{ inputs.base-ref }}
        WORKSPACE: ${{ inputs.workspace }}
