name: Versioning Action
description: Sets up contents of sources in versioned format for pushing to wordlake
inputs:
  prebuild:
    description: 'The location of the wordlake (wordlake, wordlake-staging, wordlake-dev)'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
