name: builder

on:
  workflow_call:
    secrets:
      VERCEL_GITHUB_TOKEN:
        description: 'A GitHub PAT with repo scope'
        required: true
      VERCEL_TOKEN:
        description: 'Vercel API token, account level'
        required: true
      VERCEL_ORG_ID:
        description: 'Vercel ORG token, org level'
        required: true
      VERCEL_PROJECT_ID_STAGING_PREVIEW_DOCS:
        description: 'Vercel PROJECT token, project level'
        required: true

jobs:
  preview:
    name: doc builder
    runs-on: ubuntu-latest
    env:
      SITE_REPO: docs-staging.elastic.dev
      PREBUILD: wordlake-staging
    steps:

      - name: Setup workspace
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Checkout branch into temp
        if: github.event.action != 'closed' && github.event.pull_request.merged != true
        uses: actions/checkout@v4
        with:
          path: 'tmp'
          fetch-depth: 2
          ref: refs/pull/${{ github.event.number }}/head
          persist-credentials: false

      - name: Prepare content for deploy
        if: ${{ github.event.pull_request.merged }}
        uses: actions/checkout@v4
        with:
          path: 'tmp'
          persist-credentials: false

      - name: Checkout essential repos
        uses: actions/checkout@v4
        with:
          repository: elastic/${{ env.SITE_REPO }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ env.SITE_REPO }}
          persist-credentials: false

      - name: Checkout ${{ env.PREBUILD }}
        uses: actions/checkout@v4
        with:
          repository: elastic/${{ env.PREBUILD }}
          token: ${{ secrets.VERCEL_GITHUB_TOKEN }}
          path: ${{ github.workspace }}/${{ env.PREBUILD }}

      - name: Temp sources override
        shell: bash
        run: cp -f ${{ github.workspace }}/${{ env.PREBUILD }}/.scaffold/content.js ${{ github.workspace }}/${{ env.SITE_REPO }}/config/.

      - name: Portal
        shell: bash
        run: |
          mkdir -p ${{ github.workspace }}/${{ env.PREBUILD }}/${{ github.event.repository.name }}
          rm -rf ${{ github.workspace }}/${{ env.PREBUILD }}/${{ github.event.repository.name }}/*
          rsync --ignore-missing-args -zavpm --no-l \
          --exclude='cats.mdx' \
          --exclude='infrastructure/ansible/systests/*' \
          --include='*.docnav.json' \
          --include='*.apidocs.json' \
          --include='*.mdx' \
          --include='*.png' \
          --include='*.gif' \
          --include='*.jpg' \
          --include='*.svg' \
          --include='*.jpeg' \
          --include='*.webp' \
          --include='*.devdocs.json' \
          --include='*/' \
          --exclude='*' \
          ${{ github.workspace }}/tmp/ \
          ${{ github.workspace }}/${{ env.PREBUILD }}/${{ github.event.repository.name }}/

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout Versioning action
        uses: actions/checkout@v4
        with:
          repository: elastic/workflows
          path: ./workflows

      - name: Install Versioning action dependencies
        run: npm install
        working-directory: ./workflows/.github/actions/version-content

      - name: Configure versioned worklake
        uses: ./workflows/.github/actions/version-content
        with:
          prebuild: ${{ env.PREBUILD }}
          site-repo: ${{ env.SITE_REPO }}

      # - name: Tidy before Vercel CLI run
      #   if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
      #   shell: bash
      #   run: |
      #       mkdir ${{ github.workspace }}/build/
      #       mv ${{ github.workspace }}/${{ env.PREBUILD }} ${{ github.workspace }}/build/
      #       mv ${{ github.workspace }}/${{ env.SITE_REPO }} ${{ github.workspace }}/build/

      # - name: Generate preview
      #   if: github.event.pull_request.merged != true && github.event.pull_request.closed != true
      #   id: vercel-deploy
      #   uses: elastic/builder@v25.2.0
      #   continue-on-error: false
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}  #Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STAGING_PREVIEW_DOCS }} #Required
      #     vercel-project-name: co-preview-docs
      #     working-directory: ${{ github.workspace }}/build/
      #     github-token: ${{ secrets.VERCEL_GITHUB_TOKEN }} #Optional
      #     github-comment: true # Otherwise need github-token (VERCEL_GITHUB_TOKEN)

      # - name: Portal for deploy
      #   if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == github.event.pull_request.base.repo.default_branch
      #   shell: bash
      #   run: |
      #     cd ${{ github.workspace }}/${{ env.PREBUILD }}
      #     git config user.name elasticdocs
      #     git config user.email docs-eng+elasticdocs@elastic.co
      #     git pull
      #     git add .
      #     git commit -m "New content from https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}"
      #     git push https://${{ secrets.VERCEL_GITHUB_TOKEN }}@github.com/elastic/${{ env.PREBUILD }}
